# -*- coding: utf-8 -*-
"""entrepreneurship_ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RYTv6Ac2f6MBqZbjAqTJpHPXHi1J0PnS
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

data1 = pd.read_csv("/content/Entreprenurship data.csv")

data1.head()

data1.drop(columns='Student_ID', inplace=True)

data1.head()

data1["Gender"].hist()
plt.show()

data = data1[data1["Gender"] == "Female"]

data.head()

data.drop(columns="Gender", inplace=True)

data.head()

data.reset_index(drop=True, inplace=True)

data["Entrepreneurship"].hist()
plt.show()

data.isnull().sum()

data.duplicated().sum()

data.nunique()

corr_matrix = data.corr(numeric_only=True)

plt.figure(figsize=(15,15))
sns.heatmap(corr_matrix, cmap='coolwarm', annot = True)
plt.title("Correlation Matrix")
plt.show()

from statsmodels.stats.outliers_influence import variance_inflation_factor

X = data.select_dtypes(include=['int64', 'float64'])

# Add constant
import statsmodels.api as sm
X_const = sm.add_constant(X)

# Calculate VIF for each column
vif = pd.DataFrame()
vif["feature"] = X_const.columns
vif["VIF"] = [variance_inflation_factor(X_const.values, i) for i in range(X_const.shape[1])]

print(vif)

vif = vif[vif["feature"] != "const"]

plt.figure(figsize=(10,5))
plt.bar(vif["feature"], vif["VIF"])
plt.ylabel("VIF Value")
plt.title("Variance Inflation Factor (VIF)")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

for i in data.select_dtypes(include = "object").columns:
  print(data[i].value_counts())

data.describe().T

data.select_dtypes(include = "object").describe().T

for i in data.select_dtypes(include = "number").columns:
  sns.boxplot(data = data, x = i)
  plt.show()

def whisker(col, per1, per3):
  q1, q3 = np.percentile(col, [per1, per3])
  iqr = q3 - q1

  lower_bound = q1 - (1.5 * iqr)
  upper_bound = q3 + (1.5 * iqr)
  return lower_bound, upper_bound

lw, uw = whisker(data["Starting_Salary"], 25, 75)

print('Lower Bound', lw)
print('Upper Bound', uw)

data["Starting_Salary"] = np.where(data["Starting_Salary"] > uw, uw, data["Starting_Salary"])
data["Starting_Salary"] = np.where(data["Starting_Salary"] < lw, lw, data["Starting_Salary"])

data

sns.boxplot(data = data, x = "Starting_Salary")
plt.show()

num_col = data.select_dtypes(include = "number")

skewness = num_col.skew()

print(skewness)

def status(skewness):
  results = {}
  for col, skew in skewness.items():
    if skew > 1:
      category = "High Positive / Right Skew"

    elif skew < -1:
      category = "High Negative / Left Skew"

    elif -0.5 <= skew <= 0.5:
      category = "Approximately Normal"

    else:
      category = "Moderate Skew"

    results[col] = {"skewness": skew, "category": category}

  return pd.DataFrame(results).T

print(status(skewness))

num_col.hist(figsize=(15, 10), bins=30)
plt.suptitle('Histograms of Numeric Features', fontsize=20)
plt.show()

df_encoded = pd.get_dummies(data, columns = ["Field_of_Study", "Current_Job_Level"], drop_first = True)
data = pd.DataFrame(df_encoded)

data

X = data.drop(columns = "Entrepreneurship")
y = data["Entrepreneurship"]

y = y.map({"Yes": 1, "No": 0})

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X = sc.fit_transform(X)

X.shape

X

y

y = np.asarray(y)

y

from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size = 0.3)
X_test, X_valid, Y_test, Y_valid = train_test_split(X_test, Y_test, test_size = 0.8)

print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)
print(X_valid.shape)
print(Y_valid.shape)

from sklearn.model_selection import StratifiedKFold, GridSearchCV
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix, roc_curve
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
import xgboost as xgb
import lightgbm as lgb
import shap

train_losses = []  # Store training loss per epoch
valid_losses = []  # Store validation loss per epoch
train_accuracies = []  # Track training accuracy
valid_accuracies = []  # Track validation accuracy

# Plot Loss Curve
def plot_loss_curve(train_losses, valid_losses, train_accuracies, valid_accuracies):
  plt.figure(figsize=(10, 5))
  plt.plot(train_losses, label="Train Loss", marker='o')
  plt.plot(valid_losses, label="Validation Loss", marker='o')
  plt.xlabel("Iterations")
  plt.ylabel("Loss")
  plt.title("Loss Curve")
  plt.legend()
  plt.show()

  # Plot Accuracy Curve
  plt.figure(figsize=(10, 5))
  plt.plot(train_accuracies, label="Train Accuracy", marker='o')
  plt.plot(valid_accuracies, label="Validation Accuracy", marker='o')
  plt.xlabel("Iterations")
  plt.ylabel("Accuracy")
  plt.title("Accuracy Curve")
  plt.legend()
  plt.show()

def confusion_matrix_plot(best_model, X_test, Y_test):
  y_pred_test = best_model.predict(X_test)

  from sklearn.metrics import classification_report, confusion_matrix

  cm = confusion_matrix(Y_test, y_pred_test)

  plt.figure(figsize=(8, 6))
  sns.heatmap(cm, annot=True, fmt = 'd', cmap = 'Blues')
  plt.xlabel('Predicted Labels')
  plt.ylabel('True Labels')
  plt.title('Confusion Matrix')
  plt.show()

  print(accuracy_score(Y_test, y_pred_test))
  print(classification_report(Y_test, y_pred_test))

  return y_pred_test

def auc_curve(Y_test, y_pred_test):
  fpr, tpr, thresholds = roc_curve(Y_test, y_pred_test)
  auc = roc_auc_score(Y_test, y_pred_test)

  plt.figure(figsize=(8, 6))
  plt.plot(fpr, tpr, label=f'AUC = {auc:.2f}')
  plt.plot([0, 1], [0, 1], 'k--')
  plt.legend()
  plt.xlabel('False Positive Rate')
  plt.ylabel('True Positive Rate')
  plt.title('ROC Curve')
  plt.show()

"""Logistic Regression"""

from sklearn.metrics import log_loss, accuracy_score

# Parameter grid
param_grid = {
    'penalty': ['l1', 'l2'],
    'C': [0.001, 0.01, 0.1, 1, 10],
    'solver': ['liblinear']
}

# Track best model
best_valid_accuracy = 0
best_params = None

cv_folds=5
scoring='f1'
n_jobs=-1
random_state=42

# Iterate over hyperparameters
for penalty in param_grid['penalty']:
    for C in param_grid['C']:
        for solver in param_grid['solver']:
            # Define model
            model = LogisticRegression(penalty=penalty, C=C, solver=solver, max_iter=2000)
            model.fit(X_train, Y_train)

            # Predictions
            Y_train_pred = model.predict_proba(X_train)[:, 1]
            Y_valid_pred = model.predict_proba(X_valid)[:, 1]

            # Compute log loss
            train_loss = log_loss(Y_train, Y_train_pred)
            valid_loss = log_loss(Y_valid, Y_valid_pred)

            # Compute accuracy
            train_acc = accuracy_score(Y_train, model.predict(X_train))
            valid_acc = accuracy_score(Y_valid, model.predict(X_valid))

            # Store losses and accuracies
            train_losses.append(train_loss)
            valid_losses.append(valid_loss)
            train_accuracies.append(train_acc)
            valid_accuracies.append(valid_acc)

            # Save best performing model
            if valid_acc > best_valid_accuracy:
                best_valid_accuracy = valid_acc
                best_params = (penalty, C, solver)
                best_model = LogisticRegression(penalty = penalty, C = C, solver = solver, max_iter=2000)

print(f"Best parameters: {best_params} with Validation Accuracy: {best_valid_accuracy}")

plot_loss_curve(train_losses, valid_losses, train_accuracies, valid_accuracies)

best_model.fit(X_train, Y_train)

y_pred_test = confusion_matrix_plot(best_model, X_test, Y_test)

auc_curve(Y_test, y_pred_test)

explainer = shap.LinearExplainer(best_model, X_train)
shap_values = explainer(X_test)

shap.plots.beeswarm(shap_values)

"""Decision Tree"""

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, log_loss, classification_report, confusion_matrix
import numpy as np

# Expanded parameter grid
param_grid = {
    'criterion': ['gini', 'entropy', 'log_loss'],
    'max_depth': [None, 5, 10, 20, 50],
    'min_samples_split': [2, 5, 10, 20],
    'min_samples_leaf': [1, 2, 5, 10],
    'max_features': [None, 'sqrt', 'log2'],
    'max_leaf_nodes': [None, 10, 50, 100],
    'min_impurity_decrease': [0.0, 0.01, 0.1],
    'splitter': ['best', 'random'],
    'class_weight': [None, 'balanced'],
    'ccp_alpha': [0.0, 0.01, 0.1]
}

# Track best model
best_model = None
best_params = None
best_valid_accuracy = 0
lowest_valid_loss = float("inf")
smallest_loss_gap = float("inf")

# Lists to store performance metrics
train_losses, valid_losses = [], []
train_accuracies, valid_accuracies = [], []
trained_models, trained_params = [], []

# Iterate over hyperparameters
for criterion in param_grid['criterion']:
    for max_depth in param_grid['max_depth']:
        for min_samples_split in param_grid['min_samples_split']:
            for min_samples_leaf in param_grid['min_samples_leaf']:
                for max_features in param_grid['max_features']:
                    for max_leaf_nodes in param_grid['max_leaf_nodes']:
                        for min_impurity_decrease in param_grid['min_impurity_decrease']:
                            for splitter in param_grid['splitter']:
                                for class_weight in param_grid['class_weight']:
                                    for ccp_alpha in param_grid['ccp_alpha']:
                                        # Define Decision Tree Model
                                        model = DecisionTreeClassifier(
                                            criterion=criterion,
                                            max_depth=max_depth,
                                            min_samples_split=min_samples_split,
                                            min_samples_leaf=min_samples_leaf,
                                            max_features=max_features,
                                            max_leaf_nodes=max_leaf_nodes,
                                            min_impurity_decrease=min_impurity_decrease,
                                            splitter=splitter,
                                            class_weight=class_weight,
                                            ccp_alpha=ccp_alpha
                                        )

                                        # Train model ## isi k ander he data split hota ha
                                        model.fit(X_train, Y_train)

                                        # Predictions (probabilities for log loss)
                                        Y_train_pred = model.predict_proba(X_train)[:, 1]
                                        Y_valid_pred = model.predict_proba(X_valid)[:, 1]

                                        # Compute log loss
                                        train_loss = log_loss(Y_train, Y_train_pred)
                                        valid_loss = log_loss(Y_valid, Y_valid_pred)

                                        # Compute accuracy
                                        train_acc = accuracy_score(Y_train, model.predict(X_train))
                                        valid_acc = accuracy_score(Y_valid, model.predict(X_valid))

                                        # Store trained models & parameters
                                        trained_models.append(model)
                                        trained_params.append({
                                            'criterion': criterion,
                                            'max_depth': max_depth,
                                            'min_samples_split': min_samples_split,
                                            'min_samples_leaf': min_samples_leaf,
                                            'max_features': max_features,
                                            'max_leaf_nodes': max_leaf_nodes,
                                            'min_impurity_decrease': min_impurity_decrease,
                                            'splitter': splitter,
                                            'class_weight': class_weight,
                                            'ccp_alpha': ccp_alpha
                                        })

                                        # Store losses and accuracies
                                        train_losses.append(train_loss)
                                        valid_losses.append(valid_loss)
                                        train_accuracies.append(train_acc)
                                        valid_accuracies.append(valid_acc)

                                        # Compute loss gap (overfitting indicator)
                                        loss_gap = abs(train_loss - valid_loss)

                                        # Select the best model based on:
                                        # 1. Highest validation accuracy
                                        # 2. Lowest validation loss
                                        # 3. Smallest gap between train and validation loss
                                        if valid_acc > best_valid_accuracy and valid_loss < lowest_valid_loss and loss_gap < smallest_loss_gap:
                                            best_valid_accuracy = valid_acc
                                            lowest_valid_loss = valid_loss
                                            smallest_loss_gap = loss_gap
                                            best_model = model
                                            best_params = trained_params[-1]

# Print best parameters
print(f"Best Parameters: {best_params}")
print(f"Best Validation Accuracy: {best_valid_accuracy}")
print(f"Lowest Validation Loss: {lowest_valid_loss}")
print(f"Smallest Loss Gap: {smallest_loss_gap}")

plot_loss_curve(train_losses, valid_losses, train_accuracies, valid_accuracies)

best_model.fit(X_train, Y_train)
y_pred_test = confusion_matrix_plot(best_model, X_test, Y_test)

auc_curve(Y_test, y_pred_test)

explainer = shap.TreeExplainer(best_model, X_train)
shap_values = explainer(X_test)

shap.summary_plot(shap_values, X_test)

"""Random Forest"""

# Hyperparameter grid (expanded with main parameters)
param_grid = {
    'n_estimators': [50, 100],              # Number of trees in the forest
    'max_depth': [5, 10, None],             # Maximum depth of the trees
    'min_samples_split': [2, 5],            # Minimum samples required to split an internal node
    'min_samples_leaf': [1, 2],             # Minimum samples required at a leaf node
    'max_features': ['sqrt', 'log2', None], # Number of features to consider for best split
    'bootstrap': [True, False],             # Whether bootstrap samples are used
    'criterion': ['gini', 'entropy'],       # Function to measure quality of a split
    'class_weight': [None, 'balanced'],     # Weighting for imbalanced classes
    'random_state': [21]                    # Seed for reproducibility
}

# Tracking results
train_losses, valid_losses = [], []
train_accuracies, valid_accuracies = [], []
loss_gaps = []

# Best model selection
best_valid_acc = 0
smallest_loss_gap = float("inf")
best_model = None
best_params = None

# Manual grid search
for n in param_grid['n_estimators']:
    for depth in param_grid['max_depth']:
        for min_split in param_grid['min_samples_split']:
            for min_leaf in param_grid['min_samples_leaf']:
                for max_feat in param_grid['max_features']:
                    for bootstrap in param_grid['bootstrap']:
                        for criterion in param_grid['criterion']:
                            for class_weight in param_grid['class_weight']:
                                model = RandomForestClassifier(
                                    n_estimators=n,
                                    max_depth=depth,
                                    min_samples_split=min_split,
                                    min_samples_leaf=min_leaf,
                                    max_features=max_feat,
                                    bootstrap=bootstrap,
                                    criterion=criterion,
                                    class_weight=class_weight,
                                    random_state=21
                                )
                                model.fit(X_train, Y_train)

                                # Predictions & Probabilities
                                y_train_prob = model.predict_proba(X_train)[:, 1]
                                y_valid_prob = model.predict_proba(X_valid)[:, 1]

                                # Log loss
                                train_loss = log_loss(Y_train, y_train_prob)
                                valid_loss = log_loss(Y_valid, y_valid_prob)

                                # Accuracy
                                train_acc = accuracy_score(Y_train, model.predict(X_train))
                                valid_acc = accuracy_score(Y_valid, model.predict(X_valid))

                                # Compute loss gap (indicator of overfitting)
                                loss_gap = abs(train_loss - valid_loss)

                                # Store results
                                train_losses.append(train_loss)
                                valid_losses.append(valid_loss)
                                train_accuracies.append(train_acc)
                                valid_accuracies.append(valid_acc)
                                loss_gaps.append(loss_gap)

                                # Best model selection criteria:
                                # 1. Highest validation accuracy
                                # 2. Smallest loss gap (low overfitting)
                                if valid_acc > best_valid_acc and loss_gap < smallest_loss_gap:
                                    best_valid_acc = valid_acc
                                    smallest_loss_gap = loss_gap
                                    best_params = (n, depth, min_split, min_leaf, max_feat, bootstrap, criterion, class_weight)
                                    best_model = model

# Print best parameters
print(f"\n✅ Best Parameters Found: {best_params}")
print(f"🔹 Best Validation Accuracy: {round(best_valid_acc, 3)}")
print(f"⚖️ Smallest Loss Gap (Train vs Validation): {round(smallest_loss_gap, 5)}")

plot_loss_curve(train_losses, valid_losses, train_accuracies, valid_accuracies)

best_model.fit(X_train, Y_train)

y_pred_test = confusion_matrix_plot(best_model, X_test, Y_test)

auc_curve(Y_test, y_pred_test)

explainer = shap.TreeExplainer(best_model)
shap_values = explainer.shap_values(X_test)

shap.summary_plot(shap_values, X_test)

"""K Nearest Neighbors"""

# Hyperparameter grid
param_grid = {
    'n_neighbors': [3, 5, 7, 9],
    'weights': ['uniform', 'distance'],
    'metric': ['euclidean', 'manhattan']
}

train_losses, valid_losses = [], []
train_accuracies, valid_accuracies = [], []

best_valid_acc = 0
best_params = None
best_model = None

for k in param_grid['n_neighbors']:
    for w in param_grid['weights']:
        for m in param_grid['metric']:
            model = KNeighborsClassifier(n_neighbors=k, weights=w, metric=m)
            model.fit(X_train, Y_train)

            # Probabilities for log loss
            y_train_prob = model.predict_proba(X_train)[:, 1]
            y_valid_prob = model.predict_proba(X_valid)[:, 1]

            # Loss
            train_loss = log_loss(Y_train, y_train_prob)
            valid_loss = log_loss(Y_valid, y_valid_prob)

            # Accuracy
            train_acc = accuracy_score(Y_train, model.predict(X_train))
            valid_acc = accuracy_score(Y_valid, model.predict(X_valid))

            train_losses.append(train_loss)
            valid_losses.append(valid_loss)
            train_accuracies.append(train_acc)
            valid_accuracies.append(valid_acc)

            if valid_acc > best_valid_acc:
                best_valid_acc = valid_acc
                best_params = (k, w, m)
                best_model = model

print(f"\n✅ Best Parameters: {best_params} with Validation Accuracy: {round(best_valid_acc, 3)}")

plot_loss_curve(train_losses, valid_losses, train_accuracies, valid_accuracies)

best_model.fit(X_train, Y_train)
y_pred_test = confusion_matrix_plot(best_model, X_test, Y_test)

auc_curve(Y_test, y_pred_test)

shap_values = explainer.shap_values(X_test)

shap.summary_plot(shap_values, X_test)

"""Support Vector Machines"""

# Parameter Grid for SVM
param_grid = {
    'kernel': ['linear', 'rbf', 'poly'],
    'C': [0.1, 1, 10],
    'degree': [2, 3],  # Only used for 'poly'
    'gamma': ['scale', 'auto']  # Used for 'rbf' and 'poly'
}

train_losses, valid_losses = [], []
train_accuracies, valid_accuracies = [], []

best_valid_acc = 0
best_params = None
best_model = None

for kernel in param_grid['kernel']:
    for C in param_grid['C']:
        for gamma in param_grid['gamma']:
            for degree in param_grid['degree']:

                if kernel == 'linear':
                    model = SVC(kernel=kernel, C=C, probability=True, random_state=21)
                elif kernel == 'rbf':
                    model = SVC(kernel=kernel, C=C, gamma=gamma, probability=True, random_state=21)
                else:  # poly
                    model = SVC(kernel=kernel, C=C, degree=degree, gamma=gamma, probability=True, random_state=21)

                model.fit(X_train, Y_train)

                # Predictions
                y_train_prob = model.predict_proba(X_train)[:, 1]
                y_valid_prob = model.predict_proba(X_valid)[:, 1]

                # Loss
                train_loss = log_loss(Y_train, y_train_prob)
                valid_loss = log_loss(Y_valid, y_valid_prob)

                # Accuracy
                train_acc = accuracy_score(Y_train, model.predict(X_train))
                valid_acc = accuracy_score(Y_valid, model.predict(X_valid))

                # Save
                train_losses.append(train_loss)
                valid_losses.append(valid_loss)
                train_accuracies.append(train_acc)
                valid_accuracies.append(valid_acc)

                if valid_acc > best_valid_acc:
                    best_valid_acc = valid_acc
                    best_params = (kernel, C, gamma, degree)
                    best_model = model

print(f"\n✅ Best Parameters: {best_params} with Validation Accuracy: {round(best_valid_acc, 3)}")

plot_loss_curve(train_losses, valid_losses, train_accuracies, valid_accuracies)

best_model.fit(X_train, Y_train)
y_pred_test = confusion_matrix_plot(best_model, X_test, Y_test)

auc_curve(Y_test, y_pred_test)

shap_values = explainer.shap_values(X_test)

shap.summary_plot(shap_values, X_test)

"""XGBOOST"""

!pip install xgboost
from xgboost import XGBClassifier

param_grid = {
    'n_estimators': [50, 100],
    'max_depth': [3, 5],
    'learning_rate': [0.01, 0.1],
    'subsample': [0.8, 1.0]
}

train_losses, valid_losses = [], []
train_accuracies, valid_accuracies = [], []

best_valid_acc = 0
best_params = None
best_model = None

for n in param_grid['n_estimators']:
    for d in param_grid['max_depth']:
        for lr in param_grid['learning_rate']:
            for ss in param_grid['subsample']:
                model = XGBClassifier(n_estimators=n, max_depth=d, learning_rate=lr, subsample=ss, use_label_encoder=False, eval_metric='logloss', random_state=21)
                model.fit(X_train, Y_train)

                y_train_prob = model.predict_proba(X_train)[:, 1]
                y_valid_prob = model.predict_proba(X_valid)[:, 1]

                train_loss = log_loss(Y_train, y_train_prob)
                valid_loss = log_loss(Y_valid, y_valid_prob)

                train_acc = accuracy_score(Y_train, model.predict(X_train))
                valid_acc = accuracy_score(Y_valid, model.predict(X_valid))

                train_losses.append(train_loss)
                valid_losses.append(valid_loss)
                train_accuracies.append(train_acc)
                valid_accuracies.append(valid_acc)

                if valid_acc > best_valid_acc:
                    best_valid_acc = valid_acc
                    best_params = (n, d, lr, ss)
                    best_model = model

print(f"\n✅ Best Parameters: {best_params} with Validation Accuracy: {round(best_valid_acc, 3)}")

plot_loss_curve(train_losses, valid_losses, train_accuracies, valid_accuracies)

best_model.fit(X_train, Y_train)
y_pred_test = confusion_matrix_plot(best_model, X_test, Y_test)

auc_curve(Y_test, y_pred_test)

explainer = shap.TreeExplainer(best_model, X_train)
shap_values = explainer(X_test)

shap.plots.beeswarm(shap_values)

"""Naive Bayes"""

from sklearn.naive_bayes import GaussianNB

from sklearn.naive_bayes import GaussianNB

smoothing_values = [1e-9, 1e-8, 1e-7, 1e-6]

best_valid_acc = 0
best_model = None
best_smoothing = None

train_accuracies = []
valid_accuracies = []

for smooth in smoothing_values:
    model = GaussianNB(var_smoothing=smooth)
    model.fit(X_train, Y_train)

    train_acc = accuracy_score(Y_train, model.predict(X_train))
    valid_acc = accuracy_score(Y_valid, model.predict(X_valid))

    train_accuracies.append(train_acc)
    valid_accuracies.append(valid_acc)

    if valid_acc > best_valid_acc:
        best_valid_acc = valid_acc
        best_model = model
        best_smoothing = smooth

print(f"✅ Best var_smoothing: {best_smoothing} with Validation Accuracy: {round(best_valid_acc, 3)}")

"""MLP"""

# Hyperparameter grid (expanded with main parameters)
param_grid = {
    'hidden_layer_sizes': [(32,), (64,)], 'alpha': [0.0001, 0.001], 'learning_rate': ['constant', 'adaptive'],
}

# Tracking results
train_losses, valid_losses = [], []
train_accuracies, valid_accuracies = [], []
loss_gaps = []

# Best model selection
best_valid_acc = 0
smallest_loss_gap = float("inf")
best_model = None
best_params = None

# Manual grid search
for size in param_grid['hidden_layer_sizes']:
    for hyperpar in param_grid['alpha']:
        for rate in param_grid['learning_rate']:
                                model = MLPClassifier(max_iter = 300, hidden_layer_sizes = size, alpha = hyperpar, learning_rate = rate)
                                model.fit(X_train, Y_train)

                                # Predictions & Probabilities
                                y_train_prob = model.predict_proba(X_train)[:, 1]
                                y_valid_prob = model.predict_proba(X_valid)[:, 1]

                                # Log loss
                                train_loss = log_loss(Y_train, y_train_prob)
                                valid_loss = log_loss(Y_valid, y_valid_prob)

                                # Accuracy
                                train_acc = accuracy_score(Y_train, model.predict(X_train))
                                valid_acc = accuracy_score(Y_valid, model.predict(X_valid))

                                # Compute loss gap (indicator of overfitting)
                                loss_gap = abs(train_loss - valid_loss)

                                # Store results
                                train_losses.append(train_loss)
                                valid_losses.append(valid_loss)
                                train_accuracies.append(train_acc)
                                valid_accuracies.append(valid_acc)
                                loss_gaps.append(loss_gap)

                                # Best model selection criteria:
                                # 1. Highest validation accuracy
                                # 2. Smallest loss gap (low overfitting)
                                if valid_acc > best_valid_acc and loss_gap < smallest_loss_gap:
                                    best_valid_acc = valid_acc
                                    smallest_loss_gap = loss_gap
                                    best_params = (size, hyperpar, rate)
                                    best_model = model

# Print best parameters
print(f"\n✅ Best Parameters Found: {best_params}")
print(f"🔹 Best Validation Accuracy: {round(best_valid_acc, 3)}")
print(f"⚖️ Smallest Loss Gap (Train vs Validation): {round(smallest_loss_gap, 5)}")

plot_loss_curve(train_losses, valid_losses, train_accuracies, valid_accuracies)

best_model.fit(X_train, Y_train)
confusion_matrix_plot(best_model, X_test, Y_test)

auc_curve(Y_test, y_pred_test)

explainer = shap.KernelExplainer(model.predict, X_train)
shap_values = explainer(X_test)
shap.plots.beeswarm(shap_values)

"""Adaboost"""

# Hyperparameter grid (expanded with main parameters)
param_grid = {
    'n_estimators': [50, 100],              # Number of trees in the forest
    'learning_rate': [0.01, 0.1, 1]                  # Seed for reproducibility
}

# Tracking results
train_losses, valid_losses = [], []
train_accuracies, valid_accuracies = [], []
loss_gaps = []

# Best model selection
best_valid_acc = 0
smallest_loss_gap = float("inf")
best_model = None
best_params = None

# Manual grid search
for n in param_grid['n_estimators']:
    for rate in param_grid['learning_rate']:
      model = AdaBoostClassifier(
          n_estimators=n, learning_rate=rate, random_state=21
      )
      model.fit(X_train, Y_train)
      y_train_prob = model.predict_proba(X_train)[:, 1]
      y_valid_prob = model.predict_proba(X_valid)[:, 1]

      # Log loss
      train_loss = log_loss(Y_train, y_train_prob)
      valid_loss = log_loss(Y_valid, y_valid_prob)

      # Accuracy
      train_acc = accuracy_score(Y_train, model.predict(X_train))
      valid_acc = accuracy_score(Y_valid, model.predict(X_valid))

      # Compute loss gap (indicator of overfitting)
      loss_gap = abs(train_loss - valid_loss)

      # Store results
      train_losses.append(train_loss)
      valid_losses.append(valid_loss)
      train_accuracies.append(train_acc)
      valid_accuracies.append(valid_acc)
      loss_gaps.append(loss_gap)

      # Best model selection criteria:
      # 1. Highest validation accuracy
      # 2. Smallest loss gap (low overfitting)
      if valid_acc > best_valid_acc and loss_gap < smallest_loss_gap:
        best_valid_acc = valid_acc
        smallest_loss_gap = loss_gap
        best_params = (n, rate)
        best_model = model

# Print best parameters
print(f"\n✅ Best Parameters Found: {best_params}")
print(f"🔹 Best Validation Accuracy: {round(best_valid_acc, 3)}")
print(f"⚖️ Smallest Loss Gap (Train vs Validation): {round(smallest_loss_gap, 5)}")

plot_loss_curve(train_losses, valid_losses, train_accuracies, valid_accuracies)

best_model.fit(X_train, Y_train)
y_pred_test = confusion_matrix_plot(best_model, X_test, Y_test)

auc_curve(Y_test, y_pred_test)